# Generated by Django 4.1.7 on 2023-03-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.CharField(default='Nilo here, this django II', max_length=140),
        ),
    ]
